// Regenerates preview.html — a self-contained design snapshot that the VS Code
// "HTML Preview" extension can render without a server. Inlines the production
// Tailwind CSS bundle so the preview shows the real site design, not broken
// unstyled HTML (which is what happens with the SSR HTML alone).
import { readdir, readFile, writeFile } from "node:fs/promises";

const assetsDir = ".output/public/assets";
const outFile = "preview.html";

const files = await readdir(assetsDir);
const cssFiles = files.filter((file) => file.endsWith(".css"));
const css = (
  await Promise.all(cssFiles.map((file) => readFile(`${assetsDir}/${file}`, "utf8")))
).join("\n");

const html = `<!doctype html>
<html lang="bg">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="color-scheme" content="dark" />
    <title>Преглед на дизайна — Todor Khristov Gaming</title>
    <!-- Inlined production stylesheet (generated by scripts/refresh-preview.mjs) -->
    <style>${css}</style>
  </head>
  <body class="min-h-screen bg-[#0d1a17] text-foreground antialiased">
    <header class="flex w-full items-center justify-between border-b border-border/40 bg-background/80 px-5 py-4 backdrop-blur">
      <span class="font-mono text-[0.7rem] font-bold tracking-[0.3em] text-brand uppercase">TKG<span class="text-muted-foreground">/design</span></span>
      <nav class="flex items-center gap-4 font-mono text-[0.65rem] tracking-[0.2em] text-muted-foreground uppercase">
        <a class="text-foreground" href="#">Игри</a>
        <a href="#">Музика</a>
        <a href="#">Инфо</a>
      </nav>
    </header>

    <main class="mx-auto w-full max-w-5xl px-6 py-12">
      <p class="font-mono text-[0.65rem] tracking-[0.25em] text-brand uppercase">Добре дошъл в сигнала</p>
      <h1 class="font-display mt-4 text-5xl leading-[0.95] font-black text-brand uppercase sm:text-7xl">
        Яки игри<br />и забавление
      </h1>
      <p class="mt-5 max-w-xl text-muted-foreground">
        Игри, моменти и енергия директно от командния център на Todor Khristov.
      </p>

      <div class="mt-8 flex flex-wrap items-center gap-3">
        <button type="button" class="inline-flex items-center gap-2 rounded-full bg-brand px-6 py-3 font-mono text-xs font-bold tracking-[0.2em] text-black uppercase hover:brightness-110">
          Профил на създателя
        </button>
        <button type="button" class="inline-flex items-center gap-2 rounded-full border border-border bg-surface px-6 py-3 font-mono text-xs font-bold tracking-[0.2em] text-muted-foreground uppercase transition-colors hover:text-foreground">
          Към игрите
        </button>
      </div>

      <div class="mt-12 grid grid-cols-3 items-center gap-2 rounded-2xl bg-[#0d1a17] px-4 py-3">
        <div class="flex items-center gap-2 font-mono text-[0.62rem] tracking-[0.15em] text-muted-foreground uppercase">
          <span class="size-3 rounded-full bg-[#ef4444]" aria-hidden="true" />
          Червен играч
        </div>
        <div class="text-center font-mono text-xl font-bold tracking-[0.15em] text-brand">
          0 <span class="text-muted-foreground">:</span> 0
        </div>
        <div class="flex items-center justify-end gap-2 font-mono text-[0.62rem] tracking-[0.15em] text-muted-foreground uppercase">
          Син играч
          <span class="size-3 rounded-full bg-[#3b82f6]" aria-hidden="true" />
        </div>
      </div>

      <h2 class="font-display mt-14 text-3xl font-black text-brand uppercase">Игри в ротация</h2>
      <div class="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
        <div class="rounded-2xl border border-border/40 bg-surface p-6">
          <p class="font-mono text-[0.6rem] tracking-[0.2em] text-brand uppercase">Сървайвъл</p>
          <h3 class="font-display mt-4 text-2xl font-bold text-foreground">Minecraft</h3>
          <p class="mt-2 text-sm text-muted-foreground">Серии и проекти на живо</p>
        </div>
        <div class="rounded-2xl border border-border/40 bg-surface p-6">
          <p class="font-mono text-[0.6rem] tracking-[0.2em] text-brand uppercase">Шутър</p>
          <h3 class="font-display mt-4 text-2xl font-bold text-foreground">CS2</h3>
          <p class="mt-2 text-sm text-muted-foreground">Класирани мачове</p>
        </div>
        <div class="rounded-2xl border border-border/40 bg-surface p-6">
          <p class="font-mono text-[0.6rem] tracking-[0.2em] text-brand uppercase">Моба</p>
          <h3 class="font-display mt-4 text-2xl font-bold text-foreground">Mobile Legends</h3>
          <p class="mt-2 text-sm text-muted-foreground">Ранкед битки 5v5</p>
        </div>
      </div>
    </main>

    <footer class="border-t border-border/40 px-6 py-6 text-center font-mono text-[0.6rem] tracking-[0.2em] text-muted-foreground uppercase">
      © 2026 Todor Khristov Gaming
    </footer>
  </body>
</html>
`;

await writeFile(outFile, html, "utf8");
console.log(`Wrote ${outFile} (${(Buffer.byteLength(html) / 1024).toFixed(0)} kB, css ${(Buffer.byteLength(css) / 1024).toFixed(0)} kB).`);