declare module "*.module.css" {
  const styles: {
    wrap: string;
    frame: string;
    chips: string;
    chip: string;
    chipIcon: string;
    chipName: string;
    chipRemove: string;
    editorWrap: string;
    enhancingText: string;
    field: string;
    slashMenu: string;
    slashLabel: string;
    menuItem: string;
    menuItemActive: string;
    menuName: string;
    slashEmpty: string;
    skillPill: string;
    skillPillLabel: string;
    skillPillX: string;
    row: string;
    plusWrap: string;
    iconBtn: string;
    plus: string;
    plusIcon: string;
    menu: string;
    menuIcon: string;
    menuDivider: string;
    menuSub: string;
    menuChevron: string;
    menuFlyout: string;
    menuLabel: string;
    menuBrand: string;
    menuCheck: string;
    menuPopover: string;
    popoverTitle: string;
    popoverDesc: string;
    popoverMeta: string;
    right: string;
    spinnerBtn: string;
    spinner: string;
    pill: string;
    pillExit: string;
    send: string;
    sendActive: string;
  };
  export default styles;
}
